// Code generated by protoc-gen-go. DO NOT EDIT.
// source: adminService.proto

package adminService

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type StatusNotificationInfo struct {
	Sid                  string   `protobuf:"bytes,1,opt,name=sid,proto3" json:"sid,omitempty"`
	Cid                  string   `protobuf:"bytes,2,opt,name=cid,proto3" json:"cid,omitempty"`
	Status               string   `protobuf:"bytes,3,opt,name=status,proto3" json:"status,omitempty"`
	Statdt               string   `protobuf:"bytes,4,opt,name=statdt,proto3" json:"statdt,omitempty"`
	LastTsdt             string   `protobuf:"bytes,5,opt,name=lastTsdt,proto3" json:"lastTsdt,omitempty"`
	LastTedt             string   `protobuf:"bytes,6,opt,name=lastTedt,proto3" json:"lastTedt,omitempty"`
	NowTsdt              string   `protobuf:"bytes,7,opt,name=nowTsdt,proto3" json:"nowTsdt,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StatusNotificationInfo) Reset()         { *m = StatusNotificationInfo{} }
func (m *StatusNotificationInfo) String() string { return proto.CompactTextString(m) }
func (*StatusNotificationInfo) ProtoMessage()    {}
func (*StatusNotificationInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ac4231d4b2c630, []int{0}
}

func (m *StatusNotificationInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StatusNotificationInfo.Unmarshal(m, b)
}
func (m *StatusNotificationInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StatusNotificationInfo.Marshal(b, m, deterministic)
}
func (m *StatusNotificationInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StatusNotificationInfo.Merge(m, src)
}
func (m *StatusNotificationInfo) XXX_Size() int {
	return xxx_messageInfo_StatusNotificationInfo.Size(m)
}
func (m *StatusNotificationInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StatusNotificationInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StatusNotificationInfo proto.InternalMessageInfo

func (m *StatusNotificationInfo) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *StatusNotificationInfo) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *StatusNotificationInfo) GetStatus() string {
	if m != nil {
		return m.Status
	}
	return ""
}

func (m *StatusNotificationInfo) GetStatdt() string {
	if m != nil {
		return m.Statdt
	}
	return ""
}

func (m *StatusNotificationInfo) GetLastTsdt() string {
	if m != nil {
		return m.LastTsdt
	}
	return ""
}

func (m *StatusNotificationInfo) GetLastTedt() string {
	if m != nil {
		return m.LastTedt
	}
	return ""
}

func (m *StatusNotificationInfo) GetNowTsdt() string {
	if m != nil {
		return m.NowTsdt
	}
	return ""
}

type StopTransactionInfo struct {
	No                   string   `protobuf:"bytes,1,opt,name=no,proto3" json:"no,omitempty"`
	Sid                  string   `protobuf:"bytes,2,opt,name=sid,proto3" json:"sid,omitempty"`
	Cid                  string   `protobuf:"bytes,3,opt,name=cid,proto3" json:"cid,omitempty"`
	Tbid                 string   `protobuf:"bytes,4,opt,name=tbid,proto3" json:"tbid,omitempty"`
	Tsdt                 string   `protobuf:"bytes,5,opt,name=tsdt,proto3" json:"tsdt,omitempty"`
	Tedt                 string   `protobuf:"bytes,6,opt,name=tedt,proto3" json:"tedt,omitempty"`
	Btid                 string   `protobuf:"bytes,7,opt,name=btid,proto3" json:"btid,omitempty"`
	Pow                  string   `protobuf:"bytes,8,opt,name=pow,proto3" json:"pow,omitempty"`
	Mon                  string   `protobuf:"bytes,9,opt,name=mon,proto3" json:"mon,omitempty"`
	Bprice               string   `protobuf:"bytes,10,opt,name=bprice,proto3" json:"bprice,omitempty"`
	Tbprice              string   `protobuf:"bytes,11,opt,name=tbprice,proto3" json:"tbprice,omitempty"`
	Bmon                 string   `protobuf:"bytes,12,opt,name=bmon,proto3" json:"bmon,omitempty"`
	Rcvdate              string   `protobuf:"bytes,13,opt,name=rcvdate,proto3" json:"rcvdate,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StopTransactionInfo) Reset()         { *m = StopTransactionInfo{} }
func (m *StopTransactionInfo) String() string { return proto.CompactTextString(m) }
func (*StopTransactionInfo) ProtoMessage()    {}
func (*StopTransactionInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ac4231d4b2c630, []int{1}
}

func (m *StopTransactionInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StopTransactionInfo.Unmarshal(m, b)
}
func (m *StopTransactionInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StopTransactionInfo.Marshal(b, m, deterministic)
}
func (m *StopTransactionInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StopTransactionInfo.Merge(m, src)
}
func (m *StopTransactionInfo) XXX_Size() int {
	return xxx_messageInfo_StopTransactionInfo.Size(m)
}
func (m *StopTransactionInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_StopTransactionInfo.DiscardUnknown(m)
}

var xxx_messageInfo_StopTransactionInfo proto.InternalMessageInfo

func (m *StopTransactionInfo) GetNo() string {
	if m != nil {
		return m.No
	}
	return ""
}

func (m *StopTransactionInfo) GetSid() string {
	if m != nil {
		return m.Sid
	}
	return ""
}

func (m *StopTransactionInfo) GetCid() string {
	if m != nil {
		return m.Cid
	}
	return ""
}

func (m *StopTransactionInfo) GetTbid() string {
	if m != nil {
		return m.Tbid
	}
	return ""
}

func (m *StopTransactionInfo) GetTsdt() string {
	if m != nil {
		return m.Tsdt
	}
	return ""
}

func (m *StopTransactionInfo) GetTedt() string {
	if m != nil {
		return m.Tedt
	}
	return ""
}

func (m *StopTransactionInfo) GetBtid() string {
	if m != nil {
		return m.Btid
	}
	return ""
}

func (m *StopTransactionInfo) GetPow() string {
	if m != nil {
		return m.Pow
	}
	return ""
}

func (m *StopTransactionInfo) GetMon() string {
	if m != nil {
		return m.Mon
	}
	return ""
}

func (m *StopTransactionInfo) GetBprice() string {
	if m != nil {
		return m.Bprice
	}
	return ""
}

func (m *StopTransactionInfo) GetTbprice() string {
	if m != nil {
		return m.Tbprice
	}
	return ""
}

func (m *StopTransactionInfo) GetBmon() string {
	if m != nil {
		return m.Bmon
	}
	return ""
}

func (m *StopTransactionInfo) GetRcvdate() string {
	if m != nil {
		return m.Rcvdate
	}
	return ""
}

type Result struct {
	Result               bool     `protobuf:"varint,1,opt,name=result,proto3" json:"result,omitempty"`
	ErrStr               string   `protobuf:"bytes,2,opt,name=errStr,proto3" json:"errStr,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Result) Reset()         { *m = Result{} }
func (m *Result) String() string { return proto.CompactTextString(m) }
func (*Result) ProtoMessage()    {}
func (*Result) Descriptor() ([]byte, []int) {
	return fileDescriptor_27ac4231d4b2c630, []int{2}
}

func (m *Result) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Result.Unmarshal(m, b)
}
func (m *Result) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Result.Marshal(b, m, deterministic)
}
func (m *Result) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Result.Merge(m, src)
}
func (m *Result) XXX_Size() int {
	return xxx_messageInfo_Result.Size(m)
}
func (m *Result) XXX_DiscardUnknown() {
	xxx_messageInfo_Result.DiscardUnknown(m)
}

var xxx_messageInfo_Result proto.InternalMessageInfo

func (m *Result) GetResult() bool {
	if m != nil {
		return m.Result
	}
	return false
}

func (m *Result) GetErrStr() string {
	if m != nil {
		return m.ErrStr
	}
	return ""
}

func init() {
	proto.RegisterType((*StatusNotificationInfo)(nil), "adminService.StatusNotificationInfo")
	proto.RegisterType((*StopTransactionInfo)(nil), "adminService.StopTransactionInfo")
	proto.RegisterType((*Result)(nil), "adminService.Result")
}

func init() { proto.RegisterFile("adminService.proto", fileDescriptor_27ac4231d4b2c630) }

var fileDescriptor_27ac4231d4b2c630 = []byte{
	// 404 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xa4, 0x53, 0xcb, 0xae, 0xd3, 0x30,
	0x10, 0x55, 0xd2, 0x92, 0xb6, 0x43, 0x79, 0xc8, 0xa0, 0xca, 0xaa, 0x58, 0x40, 0xc5, 0xa2, 0xab,
	0x16, 0xc1, 0x86, 0x2d, 0x20, 0x16, 0x20, 0x51, 0xa1, 0xa6, 0x62, 0xd1, 0x0d, 0x72, 0x6c, 0x17,
	0x59, 0x6a, 0xec, 0xc8, 0x99, 0xb6, 0xbf, 0xc0, 0x4f, 0xdc, 0x5f, 0xb9, 0xdf, 0x76, 0x65, 0xc7,
	0x4d, 0xd2, 0xa6, 0xbb, 0xbb, 0x9b, 0x73, 0x66, 0x3c, 0x73, 0x66, 0x74, 0x0c, 0x84, 0x89, 0x5c,
	0xe9, 0x54, 0xda, 0xa3, 0xe2, 0x72, 0x51, 0x58, 0x83, 0x86, 0x8c, 0xdb, 0xdc, 0xec, 0x3e, 0x82,
	0x49, 0x8a, 0x0c, 0x0f, 0xe5, 0xca, 0xa0, 0xda, 0x29, 0xce, 0x50, 0x19, 0xfd, 0x43, 0xef, 0x0c,
	0x79, 0x09, 0xbd, 0x52, 0x09, 0x1a, 0xbd, 0x8d, 0xe6, 0xa3, 0xb5, 0x0b, 0x1d, 0xc3, 0x95, 0xa0,
	0x71, 0xc5, 0x70, 0x25, 0xc8, 0x04, 0x92, 0xd2, 0xbf, 0xa6, 0x3d, 0x4f, 0x06, 0x74, 0xe6, 0x05,
	0xd2, 0x7e, 0xc3, 0x0b, 0x24, 0x53, 0x18, 0xee, 0x59, 0x89, 0x9b, 0x52, 0x20, 0x7d, 0xe2, 0x33,
	0x35, 0xae, 0x73, 0x52, 0x20, 0x4d, 0x5a, 0x39, 0x29, 0x90, 0x50, 0x18, 0x68, 0x73, 0xf2, 0xcf,
	0x06, 0x3e, 0x75, 0x86, 0xb3, 0xbb, 0x18, 0x5e, 0xa5, 0x68, 0x8a, 0x8d, 0x65, 0xba, 0x64, 0xbc,
	0x56, 0xff, 0x1c, 0x62, 0x6d, 0x82, 0xf8, 0x58, 0xd7, 0xdb, 0xc4, 0x9d, 0x6d, 0x7a, 0xcd, 0x36,
	0x04, 0xfa, 0x98, 0x29, 0x11, 0x34, 0xfb, 0xd8, 0x73, 0x8d, 0x5a, 0x1f, 0x7b, 0xae, 0x51, 0xe9,
	0x63, 0xc7, 0x65, 0xa8, 0x44, 0x90, 0xe7, 0x63, 0x37, 0xa1, 0x30, 0x27, 0x3a, 0xac, 0x26, 0x14,
	0xe6, 0xe4, 0x98, 0xdc, 0x68, 0x3a, 0xaa, 0x98, 0xdc, 0x68, 0x77, 0xa9, 0xac, 0xb0, 0x8a, 0x4b,
	0x0a, 0xd5, 0xa5, 0x2a, 0xe4, 0x36, 0xc6, 0x90, 0x78, 0x5a, 0x6d, 0x1c, 0xa0, 0x9f, 0xe4, 0x9a,
	0x8c, 0xc3, 0x24, 0xd7, 0x85, 0xc2, 0xc0, 0xf2, 0xa3, 0x60, 0x28, 0xe9, 0xb3, 0xaa, 0x3a, 0xc0,
	0xd9, 0x67, 0x48, 0xd6, 0xb2, 0x3c, 0xec, 0xd1, 0x4d, 0xb2, 0x3e, 0xf2, 0x57, 0x19, 0xae, 0x03,
	0x72, 0xbc, 0xb4, 0x36, 0x45, 0x1b, 0x8e, 0x13, 0xd0, 0xc7, 0xff, 0x31, 0x8c, 0xbf, 0xb4, 0xbc,
	0x42, 0x7e, 0x03, 0xe9, 0x5a, 0x85, 0xbc, 0x5f, 0x5c, 0x98, 0xec, 0xb6, 0x99, 0xa6, 0xaf, 0x2f,
	0xab, 0x82, 0xa4, 0x2d, 0xd0, 0x6e, 0x7d, 0x8a, 0x56, 0xb2, 0xfc, 0x31, 0x7d, 0xe7, 0xd1, 0x87,
	0x88, 0xfc, 0x84, 0x17, 0x57, 0xbe, 0x20, 0xef, 0xae, 0x5b, 0x76, 0x6c, 0x73, 0xbb, 0xdf, 0xd7,
	0x37, 0xdb, 0xe9, 0xb7, 0xf4, 0x57, 0xfa, 0xf7, 0xfb, 0xea, 0xcf, 0xf2, 0x9f, 0x2d, 0xf8, 0xb2,
	0x5d, 0x94, 0x25, 0xfe, 0x63, 0x7d, 0x7a, 0x08, 0x00, 0x00, 0xff, 0xff, 0xa8, 0x89, 0xe7, 0x42,
	0x6e, 0x03, 0x00, 0x00,
}
