// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v3.6.1
// source: adminService.proto

package adminService

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	AdminService_StatusNotification_FullMethodName       = "/adminService.AdminService/StatusNotification"
	AdminService_StatusNotificationStream_FullMethodName = "/adminService.AdminService/StatusNotificationStream"
	AdminService_StopTransaction_FullMethodName          = "/adminService.AdminService/StopTransaction"
)

// AdminServiceClient is the client API for AdminService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AdminServiceClient interface {
	StatusNotification(ctx context.Context, in *StatusNotificationInfo, opts ...grpc.CallOption) (*Result, error)
	StatusNotificationStream(ctx context.Context, opts ...grpc.CallOption) (AdminService_StatusNotificationStreamClient, error)
	StopTransaction(ctx context.Context, in *StopTransactionInfo, opts ...grpc.CallOption) (*Result, error)
}

type adminServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAdminServiceClient(cc grpc.ClientConnInterface) AdminServiceClient {
	return &adminServiceClient{cc}
}

func (c *adminServiceClient) StatusNotification(ctx context.Context, in *StatusNotificationInfo, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, AdminService_StatusNotification_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *adminServiceClient) StatusNotificationStream(ctx context.Context, opts ...grpc.CallOption) (AdminService_StatusNotificationStreamClient, error) {
	stream, err := c.cc.NewStream(ctx, &AdminService_ServiceDesc.Streams[0], AdminService_StatusNotificationStream_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &adminServiceStatusNotificationStreamClient{stream}
	return x, nil
}

type AdminService_StatusNotificationStreamClient interface {
	Send(*StatusNotificationInfo) error
	Recv() (*Result, error)
	grpc.ClientStream
}

type adminServiceStatusNotificationStreamClient struct {
	grpc.ClientStream
}

func (x *adminServiceStatusNotificationStreamClient) Send(m *StatusNotificationInfo) error {
	return x.ClientStream.SendMsg(m)
}

func (x *adminServiceStatusNotificationStreamClient) Recv() (*Result, error) {
	m := new(Result)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *adminServiceClient) StopTransaction(ctx context.Context, in *StopTransactionInfo, opts ...grpc.CallOption) (*Result, error) {
	out := new(Result)
	err := c.cc.Invoke(ctx, AdminService_StopTransaction_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AdminServiceServer is the server API for AdminService service.
// All implementations must embed UnimplementedAdminServiceServer
// for forward compatibility
type AdminServiceServer interface {
	StatusNotification(context.Context, *StatusNotificationInfo) (*Result, error)
	StatusNotificationStream(AdminService_StatusNotificationStreamServer) error
	StopTransaction(context.Context, *StopTransactionInfo) (*Result, error)
	mustEmbedUnimplementedAdminServiceServer()
}

// UnimplementedAdminServiceServer must be embedded to have forward compatible implementations.
type UnimplementedAdminServiceServer struct {
}

func (UnimplementedAdminServiceServer) StatusNotification(context.Context, *StatusNotificationInfo) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StatusNotification not implemented")
}
func (UnimplementedAdminServiceServer) StatusNotificationStream(AdminService_StatusNotificationStreamServer) error {
	return status.Errorf(codes.Unimplemented, "method StatusNotificationStream not implemented")
}
func (UnimplementedAdminServiceServer) StopTransaction(context.Context, *StopTransactionInfo) (*Result, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopTransaction not implemented")
}
func (UnimplementedAdminServiceServer) mustEmbedUnimplementedAdminServiceServer() {}

// UnsafeAdminServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AdminServiceServer will
// result in compilation errors.
type UnsafeAdminServiceServer interface {
	mustEmbedUnimplementedAdminServiceServer()
}

func RegisterAdminServiceServer(s grpc.ServiceRegistrar, srv AdminServiceServer) {
	s.RegisterService(&AdminService_ServiceDesc, srv)
}

func _AdminService_StatusNotification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatusNotificationInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StatusNotification(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_StatusNotification_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StatusNotification(ctx, req.(*StatusNotificationInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _AdminService_StatusNotificationStream_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(AdminServiceServer).StatusNotificationStream(&adminServiceStatusNotificationStreamServer{stream})
}

type AdminService_StatusNotificationStreamServer interface {
	Send(*Result) error
	Recv() (*StatusNotificationInfo, error)
	grpc.ServerStream
}

type adminServiceStatusNotificationStreamServer struct {
	grpc.ServerStream
}

func (x *adminServiceStatusNotificationStreamServer) Send(m *Result) error {
	return x.ServerStream.SendMsg(m)
}

func (x *adminServiceStatusNotificationStreamServer) Recv() (*StatusNotificationInfo, error) {
	m := new(StatusNotificationInfo)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func _AdminService_StopTransaction_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopTransactionInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AdminServiceServer).StopTransaction(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AdminService_StopTransaction_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AdminServiceServer).StopTransaction(ctx, req.(*StopTransactionInfo))
	}
	return interceptor(ctx, in, info, handler)
}

// AdminService_ServiceDesc is the grpc.ServiceDesc for AdminService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AdminService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "adminService.AdminService",
	HandlerType: (*AdminServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StatusNotification",
			Handler:    _AdminService_StatusNotification_Handler,
		},
		{
			MethodName: "StopTransaction",
			Handler:    _AdminService_StopTransaction_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "StatusNotificationStream",
			Handler:       _AdminService_StatusNotificationStream_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "adminService.proto",
}
